services:
  windows:
    image: dockur/windows
    container_name: windows
    environment:
      VERSION: "winxp"
      REGION: "en-US"
      KEYBOARD: "en-US"
      USERNAME: "etzyyy"
      PASSWORD: "sayangkamu2"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
      DISK_SIZE: "220G"
    volumes:
      - /dev/vda1:/storage
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
